	charmap "0", $00
	charmap "1", $01
	charmap "2", $02
	charmap "3", $03
	charmap "4", $04
	charmap "5", $05
	charmap "6", $06
	charmap "7", $07
	charmap "8", $08
	charmap "9", $09
	charmap "+", $0a
	charmap "-", $0b
	charmap "×", $0c
	charmap "/", $0d
	charmap "*", $0e
	charmap " ", $0f

	charmap "A", $10
	charmap "B", $11
	charmap "C", $12
	charmap "D", $13
	charmap "E", $14
	charmap "F", $15
	charmap "G", $16
	charmap "H", $17
	charmap "I", $18
	charmap "J", $19
	charmap "K", $1a
	charmap "L", $1b
	charmap "M", $1c
	charmap "N", $1d
	charmap "O", $1e
	charmap "P", $1f
	charmap "Q", $20
	charmap "R", $21
	charmap "S", $22
	charmap "T", $23
	charmap "U", $24
	charmap "V", $25
	charmap "W", $26
	charmap "X", $27
	charmap "Y", $28
	charmap "Z", $29

	charmap "(", $2a
	charmap ")", $2b
	charmap ":", $2c
	charmap ";", $2d
	charmap "[", $2e
	charmap "]", $2f

	charmap "a", $30
	charmap "b", $31
	charmap "c", $32
	charmap "d", $33
	charmap "e", $34
	charmap "f", $35
	charmap "g", $36
	charmap "h", $37
	charmap "i", $38
	charmap "j", $39
	charmap "k", $3a
	charmap "l", $3b
	charmap "m", $3c
	charmap "n", $3d
	charmap "o", $3e
	charmap "p", $3f
	charmap "q", $40
	charmap "r", $41
	charmap "s", $42
	charmap "t", $43
	charmap "u", $44
	charmap "v", $45
	charmap "w", $46
	charmap "x", $47
	charmap "y", $48
	charmap "z", $49

	charmap "'", $4a

	charmap "<PK>", $50
	charmap "<MN>", $51
	charmap "<PO>", $52
	charmap "<KE>", $53

	charmap "¿", $54
	charmap "¡", $55
	charmap "?", $56
	charmap "!", $57
	charmap ".", $58
	charmap "&", $59
	charmap "▷", $5a
	charmap "▶", $5b
	charmap "▼", $5c
	charmap "♂", $5d
	charmap "♀", $5e
	charmap "¥", $60 ; Poké Dollar sign
	charmap "<DOT>", $61 ; decimal point; same as "." in English
	charmap ",", $62
	charmap "“", $63
	charmap "”", $64
	charmap "·", $65
	charmap "…", $66
	charmap "○", $67
	charmap "<", $68
	charmap ">", $69

	charmap "Ä", $70
	charmap "À", $71
	charmap "Á", $72
	charmap "È", $73
	charmap "É", $74
	charmap "Ì", $75
	charmap "Í", $76
	charmap "Ö", $77
	charmap "Ò", $78
	charmap "Ó", $79
	charmap "Ü", $7a
	charmap "Ù", $7b
	charmap "Ú", $7c
	charmap "ä", $80
	charmap "à", $81
	charmap "á", $82
	charmap "â", $83
	charmap "ë", $84
	charmap "è", $85
	charmap "é", $86
	charmap "ê", $87
	charmap "ï", $88
	charmap "ì", $89
	charmap "í", $8a
	charmap "î", $8b
	charmap "ö", $8c
	charmap "ò", $8d
	charmap "ó", $8e
	charmap "ô", $8f
	charmap "ü", $90
	charmap "ù", $91
	charmap "ú", $92
	charmap "û", $93

	charmap "<c'>", $94
	charmap "<'d>", $95
	charmap "<d'>", $96
	charmap "<j'>", $97
	charmap "<'l>", $98
	charmap "<l'>", $99
	charmap "<'m>", $9a
	charmap "<m'>", $9b
	charmap "<n'>", $9c
	charmap "<p'>", $9d
	charmap "<'r>", $9e
	charmap "<'s>", $9f
	charmap "<s'>", $a0
	charmap "<'t>", $a1
	charmap "<t'>", $a2
	charmap "<u'>", $a3
	charmap "<'v>", $a4
	charmap "<y'>", $a5

	charmap "β", $a7
	charmap "ç", $a8
	charmap "Ñ", $a9
	charmap "ñ", $aa

	; control characters
	charmap "\n", $fa

PUSHC
	NEWCHARMAP font1

	charmap "0", $00
	charmap "1", $01
	charmap "2", $02
	charmap "3", $03
	charmap "4", $04
	charmap "5", $05
	charmap "6", $06
	charmap "7", $07
	charmap "8", $08
	charmap "9", $09

	charmap "A", $0a
	charmap "B", $0b
	charmap "C", $0c
	charmap "D", $0d
	charmap "E", $0e
	charmap "F", $0f
	charmap "G", $10
	charmap "H", $11
	charmap "I", $12
	charmap "J", $13
	charmap "K", $14
	charmap "L", $15
	charmap "M", $16
	charmap "N", $17
	charmap "O", $18
	charmap "P", $19
	charmap "Q", $1a
	charmap "R", $1b
	charmap "S", $1c
	charmap "T", $1d
	charmap "U", $1e
	charmap "V", $1f
	charmap "W", $20
	charmap "X", $21
	charmap "Y", $22
	charmap "Z", $23

	charmap ",", $24
	charmap ".", $25
	charmap " ", $26
	charmap "&", $27
	charmap "!", $28
	charmap "?", $29
	charmap "[", $2a
	charmap "]", $2b
	charmap "(", $2c
	charmap ")", $2d
	charmap "♥", $2e
	charmap "♠", $2f

	; hiragana characters
	charmap "ぁ", $30
	charmap "あ", $31
	charmap "ぃ", $32
	charmap "い", $33
	charmap "ぅ", $34
	charmap "う", $35
	charmap "ぇ", $36
	charmap "え", $37
	charmap "ぉ", $38
	charmap "お", $39
	charmap "か", $3a
	charmap "が", $3b
	charmap "き", $3c
	charmap "ぎ", $3d
	charmap "く", $3e
	charmap "ぐ", $3f
	charmap "け", $40
	charmap "げ", $41
	charmap "こ", $42
	charmap "ご", $43
	charmap "さ", $44
	charmap "ざ", $45
	charmap "し", $46
	charmap "じ", $47
	charmap "す", $48
	charmap "ず", $49
	charmap "せ", $4a
	charmap "ぜ", $4b
	charmap "そ", $4c
	charmap "ぞ", $4d
	charmap "た", $4e
	charmap "だ", $4f
	charmap "ち", $50
	charmap "ぢ", $51
	charmap "っ", $52
	charmap "つ", $53
	charmap "づ", $54
	charmap "て", $55
	charmap "で", $56
	charmap "と", $57
	charmap "ど", $58
	charmap "な", $59
	charmap "に", $5a
	charmap "ぬ", $5b
	charmap "ね", $5c
	charmap "の", $5d
	charmap "は", $5e
	charmap "ば", $5f
	charmap "ぱ", $60
	charmap "ひ", $61
	charmap "び", $62
	charmap "ぴ", $63
	charmap "ふ", $64
	charmap "ぶ", $65
	charmap "ぷ", $66
	charmap "へ", $67
	charmap "べ", $68
	charmap "ぺ", $69
	charmap "ほ", $6a
	charmap "ぼ", $6b
	charmap "ぽ", $6c
	charmap "ま", $6d
	charmap "み", $6e
	charmap "む", $6f
	charmap "め", $70
	charmap "も", $71
	charmap "ゃ", $72
	charmap "や", $73
	charmap "ゅ", $74
	charmap "ゆ", $75
	charmap "ょ", $76
	charmap "よ", $77
	charmap "ら", $78
	charmap "り", $79
	charmap "る", $7a
	charmap "れ", $7b
	charmap "ろ", $7c
	charmap "わ", $7e
	charmap "を", $81
	charmap "ん", $82

	; katakana characters
	charmap "ァ", $83
	charmap "ア", $84
	charmap "ィ", $85
	charmap "イ", $86
	charmap "ゥ", $87
	charmap "ウ", $88
	charmap "ェ", $89
	charmap "エ", $8a
	charmap "ォ", $8b
	charmap "オ", $8c
	charmap "カ", $8d
	charmap "ガ", $8e
	charmap "キ", $8f
	charmap "ギ", $90
	charmap "ク", $91
	charmap "グ", $92
	charmap "ケ", $93
	charmap "ゲ", $94
	charmap "コ", $95
	charmap "ゴ", $96
	charmap "サ", $97
	charmap "ザ", $98
	charmap "シ", $99
	charmap "ジ", $9a
	charmap "ス", $9b
	charmap "ズ", $9c
	charmap "セ", $9d
	charmap "ゼ", $9e
	charmap "ソ", $9f
	charmap "ゾ", $a0
	charmap "タ", $a1
	charmap "ダ", $a2
	charmap "チ", $a3
	charmap "ヂ", $a4
	charmap "ッ", $a5
	charmap "ツ", $a6
	charmap "ヅ", $a7
	charmap "テ", $a8
	charmap "デ", $a9
	charmap "ト", $aa
	charmap "ド", $ab
	charmap "ナ", $ac
	charmap "ニ", $ad
	charmap "ヌ", $ae
	charmap "ネ", $af
	charmap "ノ", $b0
	charmap "ハ", $b1
	charmap "バ", $b2
	charmap "パ", $b3
	charmap "ヒ", $b4
	charmap "ビ", $b5
	charmap "ピ", $b6
	charmap "フ", $b7
	charmap "ブ", $b8
	charmap "プ", $b9
	charmap "ヘ", $ba
	charmap "ベ", $bb
	charmap "ペ", $bc
	charmap "ホ", $bd
	charmap "ボ", $be
	charmap "ポ", $bf
	charmap "マ", $c0
	charmap "ミ", $c1
	charmap "ム", $c2
	charmap "メ", $c3
	charmap "モ", $c4
	charmap "ャ", $c5
	charmap "ヤ", $c6
	charmap "ュ", $c7
	charmap "ユ", $c8
	charmap "ョ", $c9
	charmap "ヨ", $ca
	charmap "ラ", $cb
	charmap "リ", $cc
	charmap "ル", $cd
	charmap "レ", $ce
	charmap "ロ", $cf
	charmap "ワ", $d1
	charmap "ヲ", $d4
	charmap "ン", $d5
	charmap "ヴ", $d6
	charmap "ー", $d7
	charmap "〜", $d8

	; control characters
	charmap "\n", $fa
POPC

; ASCII charmap, for save file strings
PUSHC
	NEWCHARMAP ascii
	DEF PRINTABLE_ASCII EQUS " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz\{|}~"
	FOR i, STRLEN(#PRINTABLE_ASCII)
		charmap STRSLICE(#PRINTABLE_ASCII, i, i + 1), i + $20
	ENDR
POPC
