	const_def
	const CHIKORITA ; $00
	const STEELIX   ; $01
	const CYNDAQUIL ; $02
	const TOTODILE  ; $03
	const GASTLY    ; $04
	const PIDGEY    ; $05
	const CLEFFA    ; $06
	const HITMONTOP ; $07
	const PICHU     ; $08
	const ELEKID    ; $09
	const IGGLYBUFF ; $0a
	const MAGBY     ; $0b
	const SENTRET   ; $0c
	const MARILL    ; $0d
	const PIKACHU   ; $0e
	const TOGEPI    ; $0f
	const PRIMEAPE  ; $10
	const BELLOSSOM ; $11
	const DRAGONAIR ; $12
	const JYNX      ; $13
	const DRAGONITE ; $14
	const MURKROW   ; $15
	const CROBAT    ; $16
	const CLEFAIRY  ; $17
	const KAKUNA    ; $18
	const SEEL      ; $19
DEF NUM_POKEMON EQU const_value

; Pokémon data structure (check data/pokemon.asm)
RSRESET
DEF PKMNSTRUCT_PORTRAIT_GFX RB 3 ; $00
DEF PKMNSTRUCT_UNK03 RB 3 ; $03
DEF PKMNSTRUCT_PALETTE RB 3 ; $06
DEF PKMNSTRUCT_UNK09 RB 3 ; $09
DEF PKMNSTRUCT_UNK0C RB 3 ; $0c
DEF PKMNSTRUCT_UNK0F RB 3 ; $0f
DEF PKMNSTRUCT_HURT_ANIM RB 3 ; $12
DEF PKMNSTRUCT_UNK15 RB 3 ; $15
DEF PKMNSTRUCT_UNK18 RB 3 ; $18
DEF PKMNSTRUCT_UNK1B RB 3 ; $1b
DEF PKMNSTRUCT_GARBAGE_GFX RB 3 ; $1e
DEF PKMNSTRUCT_GARBAGE_PALETTE RB 3 ; $21
DEF PKMNSTRUCT_BOARD RB   ; $24
DEF PKMNSTRUCT_UNK25 RB   ; $25
DEF PKMNSTRUCT_UNK26 RB   ; $26
DEF PKMNSTRUCT_UNK27 RB   ; $27
DEF PKMNSTRUCT_UNK28 RB   ; $28
DEF PKMNSTRUCT_UNK29 RB   ; $29
DEF PKMNSTRUCT_UNK2A RB   ; $2a
DEF PKMNSTRUCT_UNK2B RB   ; $2b
DEF PKMNSTRUCT_UNK2C RB   ; $2c
DEF PKMNSTRUCT_UNK2D RB   ; $2d
DEF PKMNSTRUCT_UNK2E RB   ; $2e
DEF PKMNSTRUCT_UNK2F RB   ; $2f
DEF PKMN_STRUCT_SIZE EQU _RS