DEF BOARD_WIDTH  EQU 6 ; how many blocks per row
DEF BOARD_HEIGHT EQU 9 ; how many blocks per column
DEF BOARD_AREA   EQU BOARD_WIDTH * BOARD_HEIGHT

; block structure constants
RSRESET
DEF BLOCKSTRUCT_UNK0 RB
DEF BLOCKSTRUCT_UNK1 RB
DEF BLOCKSTRUCT_UNK2 RB
DEF BLOCKSTRUCT_UNK3 RB
DEF BLOCKSTRUCT_UNK4 RB
DEF BLOCKSTRUCT_UNK5 RB
DEF BLOCK_STRUCT_SIZE EQU _RS
