INCLUDE "constants/hardware.inc"
INCLUDE "constants/charmap.asm"

INCLUDE "macros/asserts.asm"
INCLUDE "macros/coords.asm"
INCLUDE "macros/const.asm"
INCLUDE "macros/data.asm"
INCLUDE "macros/audio_macros.asm"
INCLUDE "macros/code.asm"
INCLUDE "macros/gfx.asm"
INCLUDE "macros/ram.asm"

INCLUDE "constants/menu_constants.asm"
INCLUDE "constants/misc_constants.asm"
INCLUDE "constants/music_constants.asm"
INCLUDE "constants/pokemon_constants.asm"
INCLUDE "constants/puzzle_constants.asm"
