INCLUDE "constants/hardware.inc"

INCLUDE "macros/const.asm"

INCLUDE "constants/board_constants.asm"
INCLUDE "constants/charmap.asm"
INCLUDE "constants/menu_constants.asm"
INCLUDE "constants/misc_constants.asm"
INCLUDE "constants/music_constants.asm"
INCLUDE "constants/pokemon_constants.asm"
INCLUDE "constants/puzzle_constants.asm"
INCLUDE "constants/text_constants.asm"

INCLUDE "macros/asserts.asm"
INCLUDE "macros/coords.asm"
INCLUDE "macros/data.asm"
INCLUDE "macros/audio_macros.asm"
INCLUDE "macros/code.asm"
INCLUDE "macros/gfx.asm"
INCLUDE "macros/text.asm"
INCLUDE "macros/ram.asm"
